name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Local Machine
        run: |
          ssh -o StrictHostKeyChecking=no your_username@your_local_machine_ip << EOF
            cd /path/to/your/application
            git pull origin main
            ./mvnw clean package
            nohup java -jar target/your-spring-boot-app.jar &
          EOF
